version: '3.1'
services:
  clamav:
    mem_limit: 800m
    image: openbridge/clamav
    container_name: clamav
    ports:
      - 3310:3310
    tty: true
    restart: unless-stopped
    tmpfs: /var/cache
    volumes:
      - clamd_data:/var/lib/clamav
      - /usr/share/tomcat:/usr/share/tomcat
      - /home:/home
      - /tmp:/tmp
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
volumes:
  clamd_data:
    driver: local
